# permissions for end users to edit imageregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageregistry-editor-role
rules:
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imageregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imageregistries/status
  verbs:
  - get
