# permissions for end users to view imagepullsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecret-viewer-role
rules:
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepullsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepullsecrets/status
  verbs:
  - get
