
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles/status
  verbs:
  - get
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepullsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepullsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepullsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepushsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepushsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imagepushsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imageregistryaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imageregistryaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - reg8stry.mgoltzsche.github.com
  resources:
  - imageregistryaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - registry.mgoltzsche.github.com
  resources:
  - imageregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.mgoltzsche.github.com
  resources:
  - imageregistries/finalizers
  verbs:
  - update
- apiGroups:
  - registry.mgoltzsche.github.com
  resources:
  - imageregistries/status
  verbs:
  - get
  - patch
  - update
